// Generated by Selenium IDE

import org.junit.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.interactions.*;

import java.util.*;

import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
public class TestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test() {
    driver.get("http://localhost/");
    driver.manage().window().setSize(new Dimension(958, 860));
    driver.findElement(By.linkText("Click me baby")).click();
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    {
      WebElement element = driver.findElement(By.id("clickMe"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    {
      WebElement element = driver.findElement(By.id("clickMe"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("clickMe")).click();
    driver.findElement(By.id("clickMe")).click();
    assertThat(driver.findElement(By.id("clicks")).getText(), is("15"));
  }
}
